import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const ROOT_DIR = path.resolve(path.dirname(__filename));
const DIST_DIR = path.join(ROOT_DIR, "dist");
const ROOT_FILE_EXTENSIONS = new Set([".html", ".css", ".js"]);
const SAFE_DIRECTORIES = ["images"];
const SAFE_IMAGE_EXTENSIONS = new Set([".png", ".jpg", ".jpeg", ".webp", ".gif", ".svg", ".ico"]);
const DEPLOY_CONFIG_FILE = "hacklab-deploy-config.js";
const DEPLOY_CONFIG_SNIPPET = `<script src="${DEPLOY_CONFIG_FILE}"></script>`;

function normalizeApiBaseUrl(rawValue = "") {
    const trimmed = String(rawValue || "").trim();
    if (!trimmed) {
        return "";
    }

    const withoutTrailingSlash = trimmed.replace(/\/+$/, "");
    if (withoutTrailingSlash.endsWith("/api")) {
        return withoutTrailingSlash;
    }

    return `${withoutTrailingSlash}/api`;
}

function normalizePagesBase(rawValue = "") {
    const trimmed = String(rawValue || "").trim().replace(/\/+$/, "");
    if (!trimmed || trimmed === "/") {
        return "";
    }

    return trimmed.startsWith("/") ? trimmed : `/${trimmed}`;
}

async function resetDist() {
    await fs.rm(DIST_DIR, { recursive: true, force: true });
    await fs.mkdir(DIST_DIR, { recursive: true });
}

async function copyRootFiles() {
    const entries = await fs.readdir(ROOT_DIR, { withFileTypes: true });

    await Promise.all(entries.map(async (entry) => {
        if (!entry.isFile()) {
            return;
        }

        const extension = path.extname(entry.name).toLowerCase();
        if (!ROOT_FILE_EXTENSIONS.has(extension)) {
            return;
        }

        if (entry.name === DEPLOY_CONFIG_FILE) {
            return;
        }

        await fs.copyFile(
            path.join(ROOT_DIR, entry.name),
            path.join(DIST_DIR, entry.name)
        );
    }));
}

async function copySafeDirectories() {
    await Promise.all(SAFE_DIRECTORIES.map(async (directoryName) => {
        const sourcePath = path.join(ROOT_DIR, directoryName);
        const targetPath = path.join(DIST_DIR, directoryName);

        try {
            await fs.access(sourcePath);
            await fs.mkdir(targetPath, { recursive: true });
            const entries = await fs.readdir(sourcePath, { withFileTypes: true });

            await Promise.all(entries.map(async (entry) => {
                if (!entry.isFile()) {
                    return;
                }

                const extension = path.extname(entry.name).toLowerCase();
                if (!SAFE_IMAGE_EXTENSIONS.has(extension)) {
                    return;
                }

                await fs.copyFile(
                    path.join(sourcePath, entry.name),
                    path.join(targetPath, entry.name)
                );
            }));
        } catch {
            // Skip directories that are not present in the repo.
        }
    }));
}

async function writeDeployConfig() {
    const apiBase = normalizeApiBaseUrl(process.env.HACKLAB_API_URL || "");
    const pagesBase = normalizePagesBase(process.env.HACKLAB_PAGES_BASE || "");
    const lines = [
        "/** Generated by build.mjs — do not edit in dist/ */",
        `window.HACKLAB_PAGES_BASE = ${JSON.stringify(pagesBase)};`,
        `window.HACKLAB_API_BASE = ${JSON.stringify(apiBase)};`
    ];

    if (apiBase) {
        lines.push('window.HACKLAB_DATA_MODE = "api";');
    }

    await fs.writeFile(
        path.join(DIST_DIR, DEPLOY_CONFIG_FILE),
        `${lines.join("\n")}\n`,
        "utf8"
    );
}

async function injectDeployConfigIntoHtmlFiles() {
    const entries = await fs.readdir(DIST_DIR, { withFileTypes: true });

    await Promise.all(entries.map(async (entry) => {
        if (!entry.isFile() || !entry.name.endsWith(".html")) {
            return;
        }

        const filePath = path.join(DIST_DIR, entry.name);
        let html = await fs.readFile(filePath, "utf8");

        if (html.includes(DEPLOY_CONFIG_FILE)) {
            return;
        }

        if (html.includes("</head>")) {
            html = html.replace("</head>", `    ${DEPLOY_CONFIG_SNIPPET}\n  </head>`);
        } else {
            html = `${DEPLOY_CONFIG_SNIPPET}\n${html}`;
        }

        await fs.writeFile(filePath, html, "utf8");
    }));
}

await resetDist();
await copyRootFiles();
await copySafeDirectories();
await writeDeployConfig();
await injectDeployConfigIntoHtmlFiles();

console.log(`GitHub Pages bundle prepared at ${DIST_DIR}`);
if (process.env.HACKLAB_API_URL) {
    console.log(`  API: ${normalizeApiBaseUrl(process.env.HACKLAB_API_URL)}`);
} else {
    console.log("  API: (not set — set HACKLAB_API_URL for production Astra on GitHub Pages)");
}
